#!/bin/bash

# Function to prompt the user for the GitHub Personal Access Token
get_access_token() {
    read -p "Enter your GitHub personal access token: " access_token
    echo "$access_token" > "$HOME/.github_access_token"
}

# Check if the repository name argument is provided
if [ -z "$1" ]; then
    echo "Please provide a repository name as an argument."
    exit 1
fi

# Check if the access token file exists and read the token from it
if [ -f "$HOME/.github_access_token" ]; then
    access_token=$(cat "$HOME/.github_access_token")
else
    # If the access token file doesn't exist, prompt the user for the token
    get_access_token
fi

# Clone the repository
git clone "https://$access_token@github.com/De-sam/$1.git"

# Check if cloning was successful
if [ $? -eq 0 ]; then
    echo "Repository cloned successfully."
else
    echo "Failed to clone the repository."
fi
